---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.rollout.name }}
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: {{ .Values.rollout.activeService }}
      previewService: {{ .Values.rollout.previewService }}
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "app.label" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "app.label" . | nindent 4 }}
    spec:
      containers:
      - name: webserver-simple
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
