apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.rollout.name }}
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: {{ .Values.rollout.activeService }}
      previewService: {{ .Values.rollout.previewService }}
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.servicePort }}
            protocol: TCP
