apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.activeService }}
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - nodePort: 31000
      protocol: TCP
      name: http
      port: {{ .Values.servicePort }}
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.previewService }}
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - nodePort: 32000
      protocol: TCP
      name: http
      port: {{ .Values.servicePort }}
  type: NodePort