# Replica count for the frontend deployment
replicaCount: 2

# name of resources such as deployment, container, service
name: frontend

# Image repository and tag for the frontend container
image:
  repository: 258591199682.dkr.ecr.ap-southeast-1.amazonaws.com/devops-jenkins-frontend
  tag: green

# Port for the frontend service
servicePort: 3000

rollout:
  name: bluegreen
  activeService: frontend-active
  previewService: frontend-preview

nodePort:
  activeService: 31000
  previewService: 32000